api_key: Tk2z7x0Y2K7tzXY6Jtps9f6X9lRiD8Vo
api_secret: N89aC8Hr7AkP7IjpXv45nIPWBudwBdk6
ws_url: ws://192.168.1.13:7880

redis:
  address: 192.168.1.15:6379

logging:
  level: info

health_port: 8081
rtmp_port: 1935
whip_port: 8080

rtc_config:
  use_external_ip: false
  udp_port: 7885
